apiVersion: v1
kind: Config
preferences: {}
current-context: default
contexts:
- name: default
  context:
    cluster: qiwi-one
    user: addon-manager
    namespace: kube-system
clusters:
- name: qiwi-one
  cluster:
    certificate-authority: K8S_CERTS_DIR/ca.crt
    server: https://MASTER_IP:443
users:
- name: addon-manager
  user:
    client-certificate: K8S_CERTS_DIR/addon-manager.crt
    client-key: K8S_KEYS_DIR/addon-manager.key
