# vim: set sw=2 :
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: control-plane
    component: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: REGISTRY/hyperkube-K8S_ARCH:K8S_VERSION
    command:
    - /bin/sh
    - -c
    - /hyperkube scheduler
      --kubeconfig=K8S_KUBECONFIG_DIR/kubeconfig-scheduler.yaml
      --leader-elect=true
      --profiling=false
      --v=2 >/var/log/kubernetes/kube-scheduler.log 2>&1
    resources:
      requests:
        cpu: 75m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 10251
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: data
      mountPath: K8S_KUBESRV_DIR
      readOnly: true
    - name: varlog
      mountPath: /var/log/kubernetes
      readOnly: false
  volumes:
  - name: data
    hostPath:
      path: K8S_KUBESRV_DIR
  - name: varlog
    hostPath:
      path: /var/log/kubernetes
