# vim: set sw=2 :
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: control-plane
    component: kube-apiserver
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: REGISTRY/hyperkube-K8S_ARCH:K8S_VERSION
    command:
    - /bin/sh
    - -c
    - /hyperkube apiserver
      --service-cluster-ip-range=SERVICE_NETWORK.1/24
      --insecure-port=API_PORT
      --secure-port=API_SECURE_PORT
      --etcd-servers=http://ETCD_IP:2379
      --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,DenyEscalatingExec,SecurityContextDeny,AlwaysPullImages
      --client-ca-file=K8S_CERTS_DIR/ca.crt
      --basic-auth-file=K8S_AUTH_DIR/basic_auth.csv
      --min-request-timeout=300
      --tls-cert-file=K8S_CERTS_DIR/kubernetes-master-bundle.pem
      --tls-private-key-file=K8S_KEYS_DIR/kubernetes-master.key
      --tls-ca-file=K8S_CERTS_DIR/ca.crt
      --kubelet-certificate-authority=K8S_CERTS_DIR/ca.crt
      --kubelet-client-certificate=K8S_CERTS_DIR/apiserver.crt
      --kubelet-client-key=K8S_KEYS_DIR/apiserver.key
      --service-account-lookup=true
      --service-account-key-file=K8S_KEYS_DIR/kubernetes-master.key
      --authorization-mode=K8S_AUTHZ_MODE
      --allow-privileged=true
      --anonymous-auth=API_ANONYMOUS_AUTH
      --profiling=false
      --audit-log-path=K8S_LOG_DIR/kube-apiserver-audit.log
      --audit-log-maxage=0
      --audit-log-maxbackup=0
      --audit-log-maxsize=1000000000
      --repair-malformed-updates=false
      --v=2 K8S_OIDC >K8S_LOG_DIR/kube-apiserver.log 2>&1
    resources:
      requests:
        cpu: 250m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: API_SECURE_PORT
        path: /healthz
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: data
      mountPath: K8S_KUBESRV_DIR
      readOnly: true
    - name: varlog
      mountPath: K8S_LOG_DIR
      readOnly: false
  volumes:
  - name: data
    hostPath:
      path: K8S_KUBESRV_DIR
  - name: varlog
    hostPath:
      path: K8S_LOG_DIR
