# vim: set sw=2 :
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  # This annotation ensures that kube-proxy does not get evicted if the node
  # supports critical pod annotation based priority scheme.
  # Note that kube-proxy runs as a static pod so this annotation does NOT have
  # any effect on rescheduler (default scheduler and rescheduler are not
  # involved in scheduling kube-proxy).
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: node
    component: kube-proxy
spec:
  hostNetwork: true
  initContainers:
  - name: touch-lock
    image: busybox
    command: ['/bin/touch', '/run/xtables.lock']
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /run
      name: run
      readOnly: false
  containers:
  - name: kube-proxy
    image: REGISTRY/hyperkube-K8S_ARCH:K8S_VERSION
    command:
    - /bin/sh
    - -c
    - echo -998 > /proc/$$$/oom_score_adj &&
      /hyperkube proxy
      --kubeconfig=K8S_KUBECONFIG_DIR/kubeconfig-kube-proxy-IP_ADDRESS.yaml
      --cluster-cidr=IP_POOL
      --iptables-sync-period=1m
      --iptables-min-sync-period=10s
      --hostname-override=IP_ADDRESS
      --v=2 >K8S_LOG_DIR/kube-proxy.log 2>&1
    # --resource-container=""
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    volumeMounts:
    - name: data
      mountPath: K8S_KUBESRV_DIR
      readOnly: true
    - name: varlog
      mountPath: K8S_LOG_DIR
      readOnly: false
    - mountPath: /run/xtables.lock
      name: iptableslock
      readOnly: false
  volumes:
  - name: data
    hostPath:
      path: K8S_KUBESRV_DIR
  - name: varlog
    hostPath:
      path: K8S_LOG_DIR
  - hostPath:
      path: /run
    name: run
  - hostPath:
      path: /run/xtables.lock
    name: iptableslock
