# vim: set sw=2 :
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: control-plane
    component: kube-controller-manager
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: REGISTRY/hyperkube-K8S_ARCH:K8S_VERSION
    command:
    - /bin/sh
    - -c
    - /hyperkube controller-manager
      --kubeconfig=K8S_KUBECONFIG_DIR/kubeconfig-controller-manager.yaml
      --service-account-private-key-file=K8S_KEYS_DIR/kubernetes-master.key
      --use-service-account-credentials=true
      --root-ca-file=K8S_CERTS_DIR/ca.crt
      --min-resync-period=3m
      --leader-elect=true
      --cluster-cidr=10.1.0.0/16
      --profiling=false
      --v=2 >/var/log/kubernetes/kube-controller-manager.log 2>&1
    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 10252
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: data
      mountPath: K8S_KUBESRV_DIR
      readOnly: true
    - name: varlog
      mountPath: /var/log/kubernetes
      readOnly: false
  volumes:
  - name: data
    hostPath:
      path: K8S_KUBESRV_DIR
  - name: varlog
    hostPath:
      path: /var/log/kubernetes
