kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-cluster-admin
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: User
  name: admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
