# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    k8s-app: k8s-proxy
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        k8s-app: k8s-proxy
    spec:
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: REGISTRY/hyperkube-ARCH:VERSION
        command:
        - /hyperkube
        - proxy
        - --kubeconfig=K8S_KUBECONFIG_DIR/kubeconfig-proxy.yaml
        - --v=2
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: K8S_KUBESRV_DIR
          readOnly: true
        - name: kubeconfig
          mountPath: K8S_KUBECONFIG_DIR
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: K8S_KUBESRV_DIR
      - name: kubeconfig
        hostPath:
          path: K8S_KUBECONFIG_DIR
