# vim: set sw=2 :
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: resource-reserver
  namespace: kube-system
  labels:
    role: resource-reserver
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      name: resource-reserver
  template:
    metadata:
      labels:
        name: resource-reserver
    spec:
      containers:
      - name: sleep-forever
        image: gcr.io/google_containers/pause:0.8.0
        resources:
          requests:
            memory: KUBELET_RESERVE_MEMORY
