# vim: set sw=2 :
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: toolbox
  labels:
    role: toolbox
spec:
  selector:
    matchLabels:
      name: toolbox
  template:
    spec:
      containers:
        - name: toolbox
          image: "hfrog/toolbox"
          command:
          - sleep
          - "604800"
    metadata:
      labels:
        name: toolbox
